const express = require('express');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const archiver = require('archiver');
let QRCode;
try { QRCode = require('qrcode'); } catch { QRCode = { toDataURL: async value => value }; }
const PDFDocument = require('pdfkit');
const ExcelJS = require('exceljs');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const { body, validationResult } = require('express-validator');
const { auth } = require('../middleware');
const { User, CommitteeMember, Event, Gallery, Donation, Expense, Receipt } = require('../models');
const router = express.Router();
const uploadDir = path.join(__dirname, '..', '..', 'uploads');
const upload = multer({ dest: uploadDir, limits: { fileSize: 5 * 1024 * 1024 }, fileFilter: (_r, file, cb) => cb(null, /^image\//.test(file.mimetype)) });
const clean = (req, res, next) => { const errors = validationResult(req); if (!errors.isEmpty()) return res.status(400).json({ message: errors.array()[0].msg }); next(); };

router.post('/auth/login', [body('username').trim().notEmpty().withMessage('Username is required'), body('password').notEmpty().withMessage('Password is required'), clean], async (req, res) => {
  const user = await User.findOne({ username: req.body.username });
  if (!user || !(await bcrypt.compare(req.body.password, user.password))) return res.status(401).json({ message: 'Invalid username or password' });
  res.json({ token: jwt.sign({ id: user._id, role: user.role }, process.env.JWT_SECRET || 'dev-secret', { expiresIn: '4h' }) });
});
router.get('/public', async (_req, res) => {
  const [members, events, gallery, donations, expenses] = await Promise.all([CommitteeMember.find().sort('name'), Event.find().sort('date'), Gallery.find().sort('-createdAt'), Donation.find().sort('-date'), Expense.find().sort('-date')]);
  const totalDonations = donations.reduce((sum, x) => sum + x.amount, 0); const totalExpenses = expenses.reduce((sum, x) => sum + x.amount, 0);
  res.json({ committeeName: process.env.COMMITTEE_NAME || 'SD Colony Ganesh Utsav Committee', members, events, gallery, donations, expenses, stats: { totalDonations, totalExpenses, balance: totalDonations - totalExpenses } });
});
router.get('/gallery/zip', async (_req, res) => { res.attachment('ganesh-gallery.zip'); const archive = archiver('zip'); archive.pipe(res); const items = await Gallery.find(); items.forEach(item => archive.file(path.join(uploadDir, item.filename), { name: item.originalName })); archive.finalize(); });
router.use(auth);
const resources = [ ['members', CommitteeMember], ['events', Event], ['expenses', Expense] ];
resources.forEach(([name, Model]) => { router.get(`/${name}`, async (_r, res) => res.json(await Model.find().sort('-createdAt'))); router.post(`/${name}`, async (req, res) => res.status(201).json(await Model.create(req.body))); router.put(`/${name}/:id`, async (req, res) => res.json(await Model.findByIdAndUpdate(req.params.id, req.body, { new: true, runValidators: true }))); router.delete(`/${name}/:id`, async (req, res) => { await Model.findByIdAndDelete(req.params.id); res.sendStatus(204); }); });
router.get('/donations', async (_r, res) => res.json(await Donation.find().sort('-date')));
router.post('/donations', async (req, res) => { const count = await Donation.countDocuments(); const receiptNumber = `GU-${new Date().getFullYear()}-${String(count + 1).padStart(4, '0')}`; const donation = await Donation.create({ ...req.body, receiptNumber }); const qrData = await QRCode.toDataURL(`${process.env.COMMITTEE_NAME || 'SD Colony Ganesh Utsav Committee'} | ${receiptNumber} | Rs. ${donation.amount}`); await Receipt.create({ receiptNumber, donation: donation._id, qrData }); res.status(201).json(donation); });
router.put('/donations/:id', async (req, res) => res.json(await Donation.findByIdAndUpdate(req.params.id, req.body, { new: true, runValidators: true })));
router.delete('/donations/:id', async (req, res) => { await Donation.findByIdAndDelete(req.params.id); res.sendStatus(204); });
router.post('/gallery', upload.array('images', 20), async (req, res) => { const items = await Promise.all(req.files.map(file => Gallery.create({ title: req.body.title || file.originalname, filename: file.filename, originalName: file.originalname, path: `/uploads/${file.filename}` }))); res.status(201).json(items); });
router.put('/gallery/:id', async (req, res) => res.json(await Gallery.findByIdAndUpdate(req.params.id, { title: req.body.title }, { new: true })));
router.delete('/gallery/:id', async (req, res) => { const item = await Gallery.findByIdAndDelete(req.params.id); if (item) fs.rmSync(path.join(uploadDir, item.filename), { force: true }); res.sendStatus(204); });
const svgText = value => String(value ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
router.get('/receipts/:number/image', async (req, res) => { const receipt = await Receipt.findOne({ receiptNumber: req.params.number }).populate('donation'); if (!receipt) return res.sendStatus(404); const donation = receipt.donation; const qr = receipt.qrData ? `<image href="${receipt.qrData}" x="650" y="95" width="125" height="125"/>` : ''; const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="900" height="570" viewBox="0 0 900 570"><rect width="900" height="570" fill="#fff8ed"/><rect x="22" y="22" width="856" height="526" rx="8" fill="#fff" stroke="#e6b33f" stroke-width="4"/><rect x="22" y="22" width="856" height="104" rx="8" fill="#8d2d24"/><text x="55" y="68" fill="#f4b942" font-family="Arial" font-size="19" font-weight="700">SD COLONY GANESH UTSAV COMMITTEE</text><text x="55" y="99" fill="#fff" font-family="Arial" font-size="16">DONATION RECEIPT</text>${qr}<text x="55" y="165" fill="#806a60" font-family="Arial" font-size="15">RECEIPT NUMBER</text><text x="55" y="192" fill="#241d1b" font-family="Arial" font-size="22" font-weight="700">${svgText(receipt.receiptNumber)}</text><text x="55" y="238" fill="#806a60" font-family="Arial" font-size="15">FLAT NUMBER</text><text x="55" y="264" fill="#241d1b" font-family="Arial" font-size="20">${svgText(donation.flatNumber || 'Not provided')}</text><text x="310" y="238" fill="#806a60" font-family="Arial" font-size="15">DONOR NAME</text><text x="310" y="264" fill="#241d1b" font-family="Arial" font-size="20">${svgText(donation.donorName)}</text><text x="55" y="310" fill="#806a60" font-family="Arial" font-size="15">MOBILE NUMBER</text><text x="55" y="336" fill="#241d1b" font-family="Arial" font-size="20">${svgText(donation.mobile || 'Not provided')}</text><text x="310" y="310" fill="#806a60" font-family="Arial" font-size="15">PAYMENT MODE</text><text x="310" y="336" fill="#241d1b" font-family="Arial" font-size="20">${svgText(donation.paymentMode || 'Cash')}</text><text x="55" y="385" fill="#806a60" font-family="Arial" font-size="15">AMOUNT</text><text x="55" y="420" fill="#8d2d24" font-family="Arial" font-size="30" font-weight="700">Rs. ${svgText(donation.amount)}</text><text x="310" y="385" fill="#806a60" font-family="Arial" font-size="15">GENERATED</text><text x="310" y="410" fill="#241d1b" font-family="Arial" font-size="17">${svgText(new Date(receipt.createdAt).toLocaleString('en-IN'))}</text><text x="55" y="480" fill="#8d2d24" font-family="Arial" font-size="16" font-weight="700">Your kindness keeps our community celebration bright. Thank you!</text><text x="665" y="480" fill="#241d1b" font-family="Arial" font-size="15">Signature: __________</text></svg>`; res.type('image/svg+xml').attachment(`${receipt.receiptNumber}.svg`).send(svg); });
router.get('/receipts/:number', async (req, res) => { const receipt = await Receipt.findOne({ receiptNumber: req.params.number }).populate('donation'); if (!receipt) return res.sendStatus(404); const doc = new PDFDocument({ margin: 50 }); res.attachment(`${receipt.receiptNumber}.pdf`); doc.pipe(res); doc.fontSize(22).fillColor('#a42b1c').text(process.env.COMMITTEE_NAME || 'SD Colony Ganesh Utsav Committee', { align: 'center' }); doc.moveDown().fontSize(16).fillColor('#222').text(`Donation Receipt: ${receipt.receiptNumber}`); doc.moveDown().fontSize(13).text(`Flat number: ${receipt.donation.flatNumber || 'Not provided'}`).text(`Donor: ${receipt.donation.donorName}`).text(`Mobile: ${receipt.donation.mobile || 'Not provided'}`).text(`Amount: Rs. ${receipt.donation.amount}`).text(`Date: ${new Date(receipt.donation.date).toLocaleDateString('en-IN')}`).text(`Payment mode: ${receipt.donation.paymentMode || 'Cash'}`).text(`Generated: ${new Date(receipt.createdAt).toLocaleString('en-IN')}`); doc.moveDown().fontSize(12).fillColor('#8d2d24').text('Your kindness keeps our community celebration bright. Thank you for supporting Ganesh Utsav.', { align: 'center' }); doc.moveDown(2).fillColor('#222').text('Signature: ____________________'); doc.end(); });
router.get('/reports/:type/:format', async (req, res) => { const Model = req.params.type === 'donations' ? Donation : Expense; const rows = await Model.find().sort('-date').lean(); if (req.params.format === 'xlsx') { const workbook = new ExcelJS.Workbook(); const sheet = workbook.addWorksheet(req.params.type); sheet.columns = Object.keys(rows[0] || { name: '', amount: '', date: '' }).map(key => ({ header: key, key })); rows.forEach(row => sheet.addRow(row)); res.attachment(`${req.params.type}.xlsx`); return workbook.xlsx.write(res); } const doc = new PDFDocument(); res.attachment(`${req.params.type}.pdf`); doc.pipe(res); doc.fontSize(18).text(`${req.params.type} report`); rows.forEach(row => doc.moveDown().fontSize(11).text(`${row.donorName || row.name} | Rs. ${row.amount} | ${new Date(row.date).toLocaleDateString('en-IN')}`)); doc.end(); });
router.get('/reports/annual-summary/pdf', async (_req, res) => { const [donations, expenses] = await Promise.all([Donation.find(), Expense.find()]); const totalDonations = donations.reduce((sum, row) => sum + row.amount, 0); const totalExpenses = expenses.reduce((sum, row) => sum + row.amount, 0); const doc = new PDFDocument(); res.attachment('annual-financial-summary.pdf'); doc.pipe(res); doc.fontSize(22).text(process.env.COMMITTEE_NAME || 'Ganesh Utsav Committee'); doc.moveDown().fontSize(16).text('Annual Financial Summary'); doc.moveDown().fontSize(13).text(`Total donations: Rs. ${totalDonations}`).text(`Total expenditure: Rs. ${totalExpenses}`).text(`Final balance: Rs. ${totalDonations - totalExpenses}`); doc.end(); });
module.exports = router;
